### ISSUE TITLE
Update compile time computations in ADO benchmarking runs

### ISSUE THREAD

**Issue by mgrang** [checkedc/checkedc-clang#1054]
We need to update the ADO benchmarking runs/scripts to handle the following:

1. Verify whether the compile time reported by LNT is relative to a baseline or is it the absolute compile time.

2. In addition to the total compile time for all benchmarks also compute the total compile time for all benchmarks that have been converted to Checked C.

**Comment by sulekhark** [comment]
A note about requirement 2 above: This measurement will give us a true picture of the impact of Checked-C-specific compiler features on the compile time. Otherwise, this impact may falsely appear to be much smaller because it gets amortized over several benchmarks that do not have Checked C annotations.
