### ISSUE TITLE
Implement bundled blocks.

### ISSUE THREAD

**Issue by dtarditi** [checkedc/checkedc-clang#276]
This work item is to implement the bundled blocks described in Section 3.5 of the Checked C version 0.6 specification.  This will needed for static checking of bounds declarations for assignments to structure members.

**Comment by wonsubkim** [comment]
For bundled block, all effects of each statement (declaration & expression) happens at the end of bundle at the same time.

As I understood, all statements are simulataneously executed at the end of bundle.
If there are multiple assignments for same variable, how can we handle this statement?
I think that this syntax is required for bounds invariance when updating some variable related to bounds declaration.

```
int a = 10;
int b = 10;
bundle {
a += 10;
b += 10;
a += 5;
b += 5;
}
printf("%d %d\n", a, b); // a = 15, b = 15? or a = 20, b = 20? or 
```
Since all statements are executed at the same time, final result is a = 15, b= 15?

**Comment by dtarditi** [comment]
This was completed by https://github.com/checkedc/checkedc-clang/pull/1172.
