### ISSUE TITLE
Unexpected illegal instruction at runtime for *p++

### ISSUE THREAD

**Issue by dopelsunce** [checkedc/checkedc-clang#863]
Input program:
```
int main(void) {
    int dst[] = { 1, 2 };
    _Array_ptr<int> p : count(2) = dst;
    *p++ = 2; // Illegal instruction
    return 0;
}
```

Clang version: the current master branch of checkedc-clang.

Expected: no illegal instruction error at runtime.

Got: an illegal instruction error at runtime.

There is no runtime error after breaking the statement `*p++;` into two lines (shown below).

```
int main(void) {
    int dst[] = { 1, 2 };
    _Array_ptr<int> p : count(2) = dst;
    *p = 2;
    p++;
    return 0;
}
```

**Comment by mgrang** [comment]
I reduced the test case further:
```
int main() {
  _Array_ptr<char> p : count(2) = "ab";
  *p++;
  return 0;
}
```

We hit the `illegal instruction` runtime error because the check for the lower bounds of the access `*p++` seems to fail.
`%_Dynamic_check.lower = icmp ule i8* %2, %1
`

On further debugging I found that changing `ule (unsigned less than or equal)` to `uge (unsigned greater than or equal)` seems to make this test pass.

The upper bound check seems to pass:
`%_Dynamic_check.upper = icmp ult i8* %1, %add.ptr`

 So it means that the lower bound of the pointer is not getting calculated correctly.

**Comment by dopelsunce** [comment]
Note that `p` has self-referential bounds, i.e., `bounds(p, p + 2)`. Use and modify a pointer with self-referential bounds at the same time is undefined in the current Checked C spec.

Another walk-around is to remove the self-referential bounds by introducing a temporary. For example, the code below is valid:
```
int main() {
  _Array_ptr<char> p : count(2) = "ab";
  _Array_ptr<char> p1 : bounds(p, p + 2) = p;
  *p1++;
  return 0;
}
```

Note that `p1` itself does not appear in its bounds.

**Comment by dtarditi** [comment]
This is incorrect code. Incrementing p is illegal since the upper bound of p + 2 is invalid. This code is now rejected at compile-time by the Checked C compiler.
